// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GeolocationController from "./geolocation_controller"
application.register("geolocation", GeolocationController)

import HeaderController from "./header_controller"
application.register("header", HeaderController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import UsersByEmailAuthController from "./users_by_email_auth_controller"
application.register("users-by-email-auth", UsersByEmailAuthController)
